### ISSUE TITLE
USER STORY: Manually adding votes to poll

### ISSUE THREAD

**Issue by MJRidder** [MJRidder/Agile-user-stories#4]
As an **administrator**
I can **add votes manually to the poll**
so that **votes that came in to me directly, can be added to the poll**

## Acceptance criteria:
* Acceptance criteria 1: Ability to manually add answers to the poll.
* Acceptance criteria 2: Drop down for sources contains the a / b / c sources that poll stats could originate from.
* Acceptance criteria 3: A log should be made when the administrator adds to the poll.

## Tasks:
- [ ] Task 1: Create button for administrator log in.
- [ ] Task 2: Identify for the user they are in an administrator environment.
- [ ] Task 3: Create option buttons for the administrator to select.
